# Model Config
model_dir : "./trained_model/"

# Config for training
max_epoch : 50000
batch_size : 30
learning_rate : 0.4321
learning_momentum : 0.8

## Learning Rate Decay
lr_decay_epoch : 2000
lr_decay_gamma : 0.1

# Config for validation
validation_epoch : 1000

# Config for model parameter
input_neuron : 4
hidden_neuron : 100
output_neuron : 3